### ISSUE TITLE
Cannot connect to X server

### ISSUE THREAD

**Issue by drewlesueur** [jeromeetienne/phantomjs-deb#1]
I am on Ubuntu, and I get this error when trying to run the hello world example.
Is there a simple solution?
`phantomjs: cannot connect to X server`

**Comment by jeromeetienne** [comment]
this repository is only for the .deb, not phantomjs itself. 

http://groups.google.com/group/phantomjs is better for phantomjs questions

**Comment by drewlesueur** [comment]
Thank you

**Comment by jeromeetienne** [comment]
closed
