### ISSUE TITLE
Couldn't find package phantomjs

### ISSUE THREAD

**Issue by playeren** [jeromeetienne/phantomjs-deb#6]
Following your steps my Ubuntu 10.04 can't find the package in question. 

steps as root:

~# add-apt-repository ppa:jerome-etienne/neoip

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /etc/apt/secring.gpg --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv [key deleted]
gpg: requesting key [key deleted] from hkp server keyserver.ubuntu.com
gpg: key [key deleted]: "Launchpad neoip" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

~# apt-get update
...
Reading package lists... Done

~# apt-get install phantomjs

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Couldn't find package phantomjs

Any suggestions?

**Comment by playeren** [comment]
I can gather that this build exclusively is for natty, so I did my own build which worked fine.

**Comment by jeromeetienne** [comment]
Excelent
